name: Gradle Release

on: workflow_dispatch

jobs:
  build:
    uses: octopusden/octopus-base/.github/workflows/common-java-gradle-release.yml@v2.1.7
    with:
      flow-type: public
      java-version: '8'
    secrets: inherit
